svnadmin create /data/svn/hbbs
svn mkdir file:///data/svn/hbbs/branches -m "create branches"
svn mkdir file:///data/svn/hbbs/tags -m "create tags"
svn mkdir file:///data/svn/hbbs/trunk -m "create trunk"
svn mkdir file:///data/svn/hbbs/tags/3.0 -m "create v3.0"
svn mkdir file:///data/svn/hbbs/tags/3.1 -m "create v3.1"
svn mkdir file:///data/svn/hbbs/tags/3.2 -m "create v3.2"
svn mkdir file:///data/svn/hbbs/tags/4.0 -m "create v4.0"
svn import hbbs_3.0 file:///data/svn/hbbs/tags/3.0 -m "import v3.0"
svn import hbbs_3.1 file:///data/svn/hbbs/tags/3.1 -m "import v3.1"
svn import hbbs_3.2 file:///data/svn/hbbs/tags/3.2 -m "import v3.2"
svn import hbbs.com file:///data/svn/hbbs/tags/4.0 -m "import v4.0"
svn import hbbs.com file:///data/svn/hbbs/trunk -m "import trunk"

svn copy file:///data/svn/hbbs/trunk file:///data/svn/hbbs/tags/4.5 -m "v4.5"
