<?php

//!!!
//!!!  do not edit, generated by script/build_route.sh
//!!!

namespace site;

use site\ControllerFactory;

/**
 * Description of ControllerRouter
 *
 * @author ikki
 */
class ControllerRouter extends ControllerFactory
{

   protected static $_route = [
      'activity'               =>  'site\\controller\\activity\\ActivityCtrler',
      'ad'                     =>  'site\\controller\\ad\\ADCtrler',
      'adm'                    =>  'site\\controller\\adm\\AdmCtrler',
      'adm/ad'                 =>  'site\\controller\\adm\\AdCtrler',
      'adm/cache'              =>  'site\\controller\\adm\\CacheCtrler',
      'bug'                    =>  'site\\controller\\bug\\BugCtrler',
      'captcha'                =>  'site\\controller\\captcha\\CaptchaCtrler',
      'comment'                =>  'site\\controller\\comment\\CommentCtrler',
      'comment/delete'         =>  'site\\controller\\comment\\DeleteCtrler',
      'comment/edit'           =>  'site\\controller\\comment\\EditCtrler',
      'file'                   =>  'site\\controller\\file\\FileCtrler',
      'file/delete'            =>  'site\\controller\\file\\DeleteCtrler',
      'file/upload'            =>  'site\\controller\\file\\UploadCtrler',
      'forum'                  =>  'site\\controller\\forum\\ForumCtrler',
      'forum/showforumhelp'    =>  'site\\controller\\forum\\ShowForumHelpCtrler',
      'help'                   =>  'site\\controller\\help\\HelpCtrler',
      'home'                   =>  'site\\controller\\home\\HomeCtrler',
      'home/ajax'              =>  'site\\controller\\home\\AJAXCtrler',
      'iostat'                 =>  'site\\controller\\iostat\\IOstatCtrler',
      'iostat/cancel'          =>  'site\\controller\\iostat\\CancelCtrler',
      'iostat/header'          =>  'site\\controller\\iostat\\HeaderCtrler',
      'iostat/sarchart'        =>  'site\\controller\\iostat\\SarchartCtrler',
      'iostat/success'         =>  'site\\controller\\iostat\\SuccessCtrler',
      'lottery'                =>  'site\\controller\\lottery\\LotteryCtrler',
      'lottery/pagenotfound'   =>  'site\\controller\\lottery\\PageNotFoundCtrler',
      'lottery/prizeshandler'  =>  'site\\controller\\lottery\\PrizesHandlerCtrler',
      'lottery/rankhandler'    =>  'site\\controller\\lottery\\RankHandlerCtrler',
      'lottery/ruleshandler'   =>  'site\\controller\\lottery\\RulesHandlerCtrler',
      'lottery/starthandler'   =>  'site\\controller\\lottery\\StartHandlerCtrler',
      'lottery/tryhandler'     =>  'site\\controller\\lottery\\TryHandlerCtrler',
      'node'                   =>  'site\\controller\\node\\NodeCtrler',
      'node/display'           =>  'site\\controller\\node\\DisplayCtrler',
      'password'               =>  'site\\controller\\password\\PasswordCtrler',
      'password/change'        =>  'site\\controller\\password\\ChangeCtrler',
      'password/forget'        =>  'site\\controller\\password\\ForgetCtrler',
      'password/reset'         =>  'site\\controller\\password\\ResetCtrler',
      'phpinfo'                =>  'site\\controller\\phpinfo\\PHPInfoCtrler',
      'pm'                     =>  'site\\controller\\pm\\PMCtrler',
      'pm/delete'              =>  'site\\controller\\pm\\DeleteCtrler',
      'pm/display'             =>  'site\\controller\\pm\\DisplayCtrler',
      'pm/reply'               =>  'site\\controller\\pm\\ReplyCtrler',
      'schools'                =>  'site\\controller\\schools\\SchoolsCtrler',
      'search'                 =>  'site\\controller\\search\\SearchCtrler',
      'single'                 =>  'site\\controller\\single\\SingleCtrler',
      'single/attend'          =>  'site\\controller\\single\\AttendCtrler',
      'single/attendee'        =>  'site\\controller\\single\\AttendeeCtrler',
      'single/chart'           =>  'site\\controller\\single\\ChartCtrler',
      'single/comment'         =>  'site\\controller\\single\\CommentCtrler',
      'single/footer'          =>  'site\\controller\\single\\FooterCtrler',
      'single/node'            =>  'site\\controller\\single\\NodeCtrler',
      'single/show'            =>  'site\\controller\\single\\ShowCtrler',
      'single/subscribe'       =>  'site\\controller\\single\\SubscribeCtrler',
      'term'                   =>  'site\\controller\\term\\TermCtrler',
      'user'                   =>  'site\\controller\\user\\UserCtrler',
      'user/activate'          =>  'site\\controller\\user\\ActivateCtrler',
      'user/delete'            =>  'site\\controller\\user\\DeleteCtrler',
      'user/display'           =>  'site\\controller\\user\\DisplayCtrler',
      'user/edit'              =>  'site\\controller\\user\\EditCtrler',
      'user/login'             =>  'site\\controller\\user\\LoginCtrler',
      'user/logout'            =>  'site\\controller\\user\\LogoutCtrler',
      'user/password'          =>  'site\\controller\\user\\PasswordCtrler',
      'user/pm'                =>  'site\\controller\\user\\PmCtrler',
      'user/register'          =>  'site\\controller\\user\\RegisterCtrler',
      'user/su'                =>  'site\\controller\\user\\SuCtrler',
      'user/username'          =>  'site\\controller\\user\\UsernameCtrler',
      'weather'                =>  'site\\controller\\weather\\WeatherCtrler',
      'wedding'                =>  'site\\controller\\wedding\\WeddingCtrler',
      'wedding/add'            =>  'site\\controller\\wedding\\AddCtrler',
      'wedding/checkin'        =>  'site\\controller\\wedding\\CheckinCtrler',
      'wedding/edit'           =>  'site\\controller\\wedding\\EditCtrler',
      'wedding/gift'           =>  'site\\controller\\wedding\\GiftCtrler',
      'wedding/join'           =>  'site\\controller\\wedding\\JoinCtrler',
      'wedding/listall'        =>  'site\\controller\\wedding\\ListAllCtrler',
      'wedding/login'          =>  'site\\controller\\wedding\\LoginCtrler',
      'wedding/logout'         =>  'site\\controller\\wedding\\LogoutCtrler',
      'yp'                     =>  'site\\controller\\yp\\YPCtrler',
      'yp/showyellowpagehome'  =>  'site\\controller\\yp\\ShowYellowPageHomeCtrler',
      'yp/showyellowpagejoin'  =>  'site\\controller\\yp\\ShowYellowPageJoinCtrler',
   ];

}
//__END_OF_FILE__
