<?php
// do not edit, generated by script/build_route.sh

$route = [
   'home' => 'site\\controller\\Home',
   'activity' => 'site\\controller\\Activity',
   'adm' => 'site\\controller\\Adm',
   'ad' => 'site\\controller\\AD',
   'bug' => 'site\\controller\\Bug',
   'cachemanager' => 'site\\controller\\CacheManager',
   'captcha' => 'site\\controller\\Captcha',
   'comment' => 'site\\controller\\Comment',
   'file' => 'site\\controller\\File',
   'forum' => 'site\\controller\\Forum',
   'help' => 'site\\controller\\Help',
   'home' => 'site\\controller\\Home',
   'iostat' => 'site\\controller\\IOstat',
   'lottery' => 'site\\controller\\Lottery',
   'node' => 'site\\controller\\Node',
   'password' => 'site\\controller\\Password',
   'phpinfo' => 'site\\controller\\PHPInfo',
   'pm' => 'site\\controller\\PM',
   'schools' => 'site\\controller\\Schools',
   'search' => 'site\\controller\\Search',
   'single' => 'site\\controller\\Single',
   'term' => 'site\\controller\\Term',
   'user' => 'site\\controller\\User',
   'weather' => 'site\\controller\\Weather',
   'wedding' => 'site\\controller\\Wedding',
   'yp' => 'site\\controller\\YP',
];

//__END_OF_FILE__
