#!/bin/bash

sitedir=/home/web/www.houstonbbs.com

cat > /tmp/route.php <<'EOF'
<?php
// do not edit, generated by script/build_route.sh

$route = array(
EOF

for i in $sitedir/controller/*.php; do
    ctrler=$(basename $i .php)
    uri="$(echo $ctrler | tr '[A-Z]' '[a-z]')"

    echo '   '\'$uri\'' => '\''site\\controller\\'$ctrler\'',' >> /tmp/route.php
done

cat >> /tmp/route.php <<'EOF'
);

//__END_OF_FILE__
EOF

mv -f $sitedir/route.php $sitedir/route.php.backup && mv -f /tmp/route.php $sitedir/route.php